<?php
define("SECURITYSVC_URL_DENIED",			"The URL which you are trying to access is denied by security system.");
define("SECURITYSVC_DOMAIN_DENIED",			"The Domain which you are trying to access is denied by security system.");
define("SECURITYSVC_AGENT_DENIED",			"The Browser Agent is denied by security system.");
define("SECURITYSVC_IPADDR_DENIED",			"Your IP address is denied by security system.");
define("SECURITYSVC_POST_DENIED",			"The Data which you are trying to post is denied by security system.");
define("SECURITYSVC_GET_DENIED",			"The Resource which you are trying to access is denied by security system.");
?>