<?php
define("VALIDATESVC_DATE_INVALID",				"Please enter a valid date on %s . YYYY-MM-DD .");
define("VALIDATESVC_EMAIL_INVALID",				"Please enter a valid email address on %s. abc@domain.tld .");
define("VALIDATESVC_PHONE_INVALID",				"Please enter a valid telephone number on %s. ###-###-####.");
define("VALIDATESVC_ZIP_INVALID",				"Please enter a valid zip code on %s. ##### or #####-####");
define("VALIDATESVC_SOCIAL_INVALID",			"Please enter a valid US social security number on %s. ###-##-####");
define("VALIDATESVC_CREDIT_INVALID",			"Please enter a valid card number on %s.");
define("VALIDATESVC_STREET_INVALID",			"Please enter a valid US street address on %s. #### Memory Lane");
define("VALIDATESVC_PASSWORD_NOT_STRONG",		"Please enter a password containing atleast 8 characters using both upper and lower cases characters as well as atleast one digit.");
define("VALIDATESVC_INVALID",					"Please enter a valid %s.");
define("VALIDATESVC_SHORTER_THAN",				"Please enter a valid %s which should be shorter than %s charactors.");
define("VALIDATESVC_BETWEEN_LENGTH",			"Please enter a valid %s which should be between %s and %s charactors.");
define("VALIDATESVC_LONGER_THAN",				"Please enter a valid %s which should be longer than %s charactors.");
define("VALIDATESVC_LESS_THAN",					"Please enter a valid %s which should be less than %s .");
define("VALIDATESVC_GREATER_THAN",				"Please enter a valid %s which should be greater than %s .");
define("VALIDATESVC_BETWEEN",					"Please enter a valid %s which should be between %s and %s .");
?>