LOGIN					=	"Login"
USER_MANAGEMENT			=	"User Mgmt"
EVENT_LOG				=	"Event Log"
EMAIL_LOG				=	"Email Log"
EMAIL_QUEUE				=	"Email Queue"

MSG_EVENT_USER_NEW		=	"User Created. User Login: %s, Password encrypt: %s."
MSG_EVENT_USER_EDIT		=	"User Modified.User Login: %s, Password encrypt: %s."
MSG_EVENT_USER_DELETE	=	"User Deleted. User Login: %s."

MSG_LOGIN_SUCCESSFUL	=	"User: %s Login successful from IP: %s ."
MSG_LOGIN_FAILED		=	"User: %s Login failed from IP: %s by using password: %s."

MSG_GET_PASSWORD_TOKEN 	= 	"User %s has requested a password token from IP %s ."
MSG_USER_REGISTERED		=	"User Registered. User Login: %s, registered from IP: %s."
MSG_RESET_PASSWORD_BY_TOKEN = "User %s has reset password  sucessful by token."
MSG_USER_RESET_PASSWORD = 	"User Password Reset. User password has been reset sucessful."
MSG_LOGOUT_SUCCESSFUL	=	"User: %s Logout successful."

MSG_EVENT_LOG_EXPORT	=	"User has exported all event log records."
MSG_EVENT_LOG_CLEAR		=	"User has deleted all event log records."

MSG_EMAIL_LOG_EXPORT	=	"User has exported all email log records."
MSG_EMAIL_LOG_CLEAR		=	"User has deleted all email log records."

MSG_EMAIL_QUEUE_SEND_ALL_PENDING	=	"User has manual sent all pending emails from queue."
MSG_EMAIL_QUEUE_DELETE_SENT	=	"User has deleted all sent emails from queue."
MSG_EMAIL_QUEUE_DELETE_ALL	=	"User has deleted all emails from queue."
